#define SCREEN_WIDTH  1200 //´°¿Ú¿í¸ß
#define SCREEN_HEIGHT 1200

enum GAMESTAT_EUNM
{
	ENUM_GAME_STOP,
	ENUM_GAME_PAUSE,
	ENUM_GAME_BEGIN,
	ENUM_GAME_WIN,
	ENUM_GAME_LOST,
	ENUM_CARDGAME_BEGIN,
};

enum ITEMSTAT_EUNM
{
	ENUM_ITEM_WAIT,
	ENUM_ITEM_EFFECT,
	ENUM_ITEM_TIMEOVER,
};


enum PLAYERSTAT_EUNM
{
	ENUM_PLAY_NORMAL,
	ENUM_PLAY_VISIBLE,
	ENUM_PLAY_UNCONQUERABLE,
};


enum ENTITYSTAT_EUNM
{
	ENUM_ENTITY_NORMAL,
	ENUM_ENTITY_NOTALIVE,
	ENUM_ENTITY_DESTORYING,
	ENUM_ENTITY_NEEDDESTORY,


};

enum ENTITYTYPE_EUNM
{
	ENUM_BIRDTYPE_REDANGRYBIRD,
	ENUM_BIRDTYPE_RUSNANGRYBIRD,
	ENUM_BIRDTYPE_STRONGANGRYBIRD,
	ENUM_BIRDTYPE_SMARTANGRYBIRD,
	ENUM_BIRDTYPE_EGGBIRD,
	ENUM_BIRDTYPE_CREATEEGGBIRD,
	ENUM_BIRDTYPE_SMALLBIRD,



	ENUM_BUTTLETYPE_NORMAL =30,

	ENUM_ITEMTYPE_ADDSPEED=50,
	ENUM_ITEMTYPE_STOPALLBIRDS,
	ENUM_ITEMTYPE_ADDLIFE,
	ENUM_ITEMTYPE_BECOMEBIRD,
	ENUM_ITEMTYPE_REALPIG,
	ENUM_ITEMTYPE_QUEENKISS,

};

enum BGPRINTTYPE_ENUM
{
	ENUM_BG_NORMAL,
	ENUM_BG_BACK,
	ENUM_BG_NEEDRESUME,
};
